#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord desktop='^3' follow=off
bspc rule -a feh state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
#bspc config focused_border_color        "#6c71c4"
#bspc config normal_border_color         "#073642"
#bspc config active_border_color         "#073642"

bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"
bspc config presel_feedback_color       "#87FFAF"
bspc config focused_border_color        "#87FFAF"


#
# Autostart
#

conky &
xset r rate 300 40 &
~/.config/polybar/launch.sh &
/usr/bin/dunst --print >> ~/.config/dunst/notification.log & 
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --bg-scale /home/vadim/Pictures/image_wallpaper.png &
picom --config=.config/picom.conf &
#picom &
nm-applet --indicator &
xsetroot -cursor_name left_ptr &
#~/.config/bspwm/scripts/low_bat_notifier.sh &
blueman-applet &
#kdeconnect-indicator &
thunar --daemon &
dunst -config=.config/dunst/dunstrc &
